from datetime import datetime
import numpy as np

raw_wo_table = {
    "wo_1": {
        "AssetNumber": "012",
        "Organization": "Active",
        "Out of Service Date": np.NAN,
        "Department": "99",
        "Agency": "POL Police Department",
        "Assigned Asset Shop": "LWN",
        "Veh Year": 2012,
        "Make": "CHEVROLET",
        "Model": "CAPRICE",
        "Class": "Police Vehicle",
        "Vehicle Type": "Marked Police",
        "Pm Length at the time": "3 Months",
        "DueMonthDate": datetime(2021, 7, 1),
        "Calendar Year": 2021,
        "Fiscal Year": 2022,
        "Month": 7,
        "MonthName": "July",
        "PM Due Date": datetime(2021, 7, 5),
        "Done At": datetime(2021, 6, 30, 10, 38, 38),
        "Work Order Date": datetime(2021, 6, 28, 10, 48, 0),
        "Days Late No10%": 0,
        "Days Late 10%": 0,
        "Leeway": 9.125,
        "OnTime": 1,
        "Late": 0,
        "OffSchedule": 1,
        "OnSchedule": 0,
        "Closed Date": datetime(2021, 6, 30, 13, 39, 0),
        "Days In Shop": 2.125,
        "Number of Repairs": 6,
        "Total Work Order Cost": 1166.803,
        "Labor hours": 6.59806,
        "Sublet Hours": 0,
        "Symptom": "pm",
        "RoadCall": np.NAN,
        "Accident": np.NAN,
        "Work Order": 851790,
        "Preceding PM Miles": 0,
        "This PM Mileage": 27059,
        "Miles Driven": 27059,
    },
    "wo_2": {
        "AssetNumber": "012",
        "Organization": "Active",
        "Out of Service Date": np.NAN,
        "Department": "99",
        "Agency": "POL Police Department",
        "Assigned Asset Shop": "LWN",
        "Veh Year": 2012,
        "Make": "CHEVROLET",
        "Model": "CAPRICE",
        "Class": "Police Vehicle",
        "Vehicle Type": "Marked Police",
        "Pm Length at the time": "3 Months",
        "DueMonthDate": datetime(2021, 8, 1),
        "Calendar Year": 2021,
        "Fiscal Year": 2022,
        "Month": 8,
        "MonthName": "August",
        "PM Due Date": datetime(2021, 8, 6),
        "Done At": datetime(2021, 9, 1, 16, 42, 21),
        "Work Order Date": datetime(2021, 8, 30, 13, 50, 0),
        "Days Late No10%": 23.916,
        "Days Late 10%": 23.916,
        "Leeway": 9.125,
        "OnTime": 0,
        "Late": 1,
        "OffSchedule": 1,
        "OnSchedule": 0,
        "Closed Date": datetime(2021, 9, 1, 16, 42, 36),
        "Days In Shop": 2.125,
        "Number of Repairs": 3,
        "Total Work Order Cost": 383.489,
        "Labor hours": 3.02055,
        "Sublet Hours": 0,
        "Symptom": "PM DUE",
        "RoadCall": np.NAN,
        "Accident": np.NAN,
        "Work Order": 858400,
        "Preceding PM Miles": 27059,
        "This PM Mileage": 27159,
        "Miles Driven": 100,
    },
    "wo_3": {
        "AssetNumber": "013",
        "Organization": "Active",
        "Out of Service Date": np.NAN,
        "Department": "99",
        "Agency": "POL Police Department",
        "Assigned Asset Shop": "LWN",
        "Veh Year": 2013,
        "Make": "CHEVROLET",
        "Model": "CAPRICE",
        "Class": "Police Vehicle",
        "Vehicle Type": "Marked Police",
        "Pm Length at the time": "3 Months",
        "DueMonthDate": datetime(2021, 9, 1),
        "Calendar Year": 2021,
        "Fiscal Year": 2022,
        "Month": 9,
        "MonthName": "September",
        "PM Due Date": datetime(2021, 9, 24),
        "Done At": datetime(2021, 12, 14, 7, 30, 42),
        "Work Order Date": datetime(2021, 12, 8, 8, 37, 0),
        "Days Late No10%": 75.375,
        "Days Late 10%": 75.375,
        "Leeway": 9.125,
        "OnTime": 0,
        "Late": 1,
        "OffSchedule": 1,
        "OnSchedule": 0,
        "Closed Date": datetime(2021, 12, 14, 7, 30, 42),
        "Days In Shop": 5.958333,
        "Number of Repairs": 5,
        "Total Work Order Cost": 738.818,
        "Labor hours": 5.645,
        "Sublet Hours": 0,
        "Symptom": "ODPM - 09/24/2021  -74 Days",
        "RoadCall": "Y",
        "Accident": np.NAN,
        "Work Order": 868813,
        "Preceding PM Miles": 0,
        "This PM Mileage": 62524,
        "Miles Driven": 62524,
    },
}

intermediate_wo_table = {
    "wo_1": {
        "road_call": 0,
        "accident": 0,
    },
    "wo_2": {
        "road_call": 0,
        "accident": 0,
    },
    "wo_3": {
        "road_call": 1,
        "accident": 0,
    },
}

prepared_wo_table = {
    "wo_1": {
        "asset_number": "012",
        "organization": "Active",
        "out_of_service_date": np.NAN,
        "department": "99",
        "agency": "POL Police Department",
        "assigned_asset_shop": "LWN",
        "vehicle_year": 2012,
        "make": "CHEVROLET",
        "model": "CAPRICE",
        "class": "Police Vehicle",
        "vehicle_type": "Marked Police",
        "pm_cycle_length": "3 Months",
        "due_month_date": datetime(2021, 7, 1),
        "calendar_year": 2021,
        "fiscal_year": 2022,
        "month_number": 7,
        "month_name": "July",
        "pm_due_date": datetime(2021, 7, 5),
        "done_at_date": datetime(2021, 6, 30, 10, 38, 38),
        "work_order_date": datetime(2021, 6, 28, 10, 48, 0),
        "days_late": 0.0,
        "days_late_adjusted": 0.0,
        "leeway": 9.125,
        "is_ontime": True,
        "is_late": False,
        "is_off_schedule": True,
        "is_on_schedule": False,
        "closed_date": datetime(2021, 6, 30, 13, 39, 0),
        "days_in_shop": 2.125,
        "number_of_repairs": 6,
        "work_order_total_cost": 1166.803,
        "labor_hours": 6.59806,
        "sublet_hours": 0.0,
        "symptom": "pm",
        "road_call": False,
        "accident": False,
        "work_order_number": "851790",
        "preceding_pm_mileage": 0.0,
        "current_pm_mileage": 27059.0,
        "miles_driven": 27059.0,
    },
    "wo_2": {
        "asset_number": "012",
        "organization": "Active",
        "out_of_service_date": np.NAN,
        "department": "99",
        "agency": "POL Police Department",
        "assigned_asset_shop": "LWN",
        "vehicle_year": 2012,
        "make": "CHEVROLET",
        "model": "CAPRICE",
        "class": "Police Vehicle",
        "vehicle_type": "Marked Police",
        "pm_cycle_length": "3 Months",
        "due_month_date": datetime(2021, 8, 1),
        "calendar_year": 2021,
        "fiscal_year": 2022,
        "month_number": 8,
        "month_name": "August",
        "pm_due_date": datetime(2021, 8, 6),
        "done_at_date": datetime(2021, 9, 1, 16, 42, 21),
        "work_order_date": datetime(2021, 8, 30, 13, 50, 0),
        "days_late": 23.916,
        "days_late_adjusted": 23.916,
        "leeway": 9.125,
        "is_ontime": False,
        "is_late": True,
        "is_off_schedule": True,
        "is_on_schedule": False,
        "closed_date": datetime(2021, 9, 1, 16, 42, 36),
        "days_in_shop": 2.125,
        "number_of_repairs": 3,
        "work_order_total_cost": 383.489,
        "labor_hours": 3.02055,
        "sublet_hours": 0.0,
        "symptom": "PM DUE",
        "road_call": False,
        "accident": False,
        "work_order_number": "858400",
        "preceding_pm_mileage": 27059.0,
        "current_pm_mileage": 27159.0,
        "miles_driven": 100.0,
    },
    "wo_3": {
        "asset_number": "013",
        "organization": "Active",
        "out_of_service_date": np.NAN,
        "department": "99",
        "agency": "POL Police Department",
        "assigned_asset_shop": "CAR",
        "vehicle_year": 2013,
        "make": "CHEVROLET",
        "model": "CAPRICE",
        "class": "Police Vehicle",
        "vehicle_type": "Marked Police",
        "pm_cycle_length": "3 Months",
        "due_month_date": datetime(2021, 9, 1),
        "calendar_year": 2021,
        "fiscal_year": 2022,
        "month_number": 9,
        "month_name": "September",
        "pm_due_date": datetime(2021, 9, 24),
        "done_at_date": datetime(2021, 12, 14, 7, 30, 42),
        "work_order_date": datetime(2021, 12, 8, 8, 37, 0),
        "days_late": 75.375,
        "days_late_adjusted": 75.375,
        "leeway": 9.125,
        "is_ontime": False,
        "is_late": True,
        "is_off_schedule": True,
        "is_on_schedule": False,
        "closed_date": datetime(2021, 12, 14, 7, 30, 42),
        "days_in_shop": 5.958333,
        "number_of_repairs": 5,
        "work_order_total_cost": 738.818,
        "labor_hours": 5.645,
        "sublet_hours": 0.0,
        "symptom": "ODPM - 09/24/2021  -74 Days",
        "road_call": True,
        "accident": False,
        "work_order_number": "868813",
        "preceding_pm_mileage": 0.0,
        "current_pm_mileage": 62524.0,
        "miles_driven": 62524.0,
    },
}
